# Focus Assist Data

> Auto-generated by Focus Assist. Edit with care.

## Settings

- **Focus Duration:** 25 min
- **Short Break:** 5 min
- **Long Break:** 15 min
- **Sessions Before Long Break:** 4
- **Current Streak:** 0 days

## Preferences

- **Notification Sound:** gentle-chime
- **Obsidian Vault Path:** 
- **Obsidian Auto Sync:** false

## Tasks

_No tasks yet._

## Pomodoros

_No pomodoros yet._

## Daily Stats

_No stats yet._
